// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelCompanion.Api.Data;

#nullable disable

namespace TravelCompanion.Api.Data.Migrations
{
    [DbContext(typeof(TravelCompanionDbContext))]
    [Migration("20260919154158_AddAnalyticsDailyAggregates")]
    partial class AddAnalyticsDailyAggregates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecommendationTravelPackages", b =>
                {
                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TravelPackageId")
                        .HasColumnType("uuid");

                    b.HasKey("RecommendationId", "TravelPackageId");

                    b.HasIndex("TravelPackageId");

                    b.ToTable("RecommendationTravelPackages", (string)null);
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("TemporaryPasswordIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.AppUserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Trip");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("TripId", "RevokedAt");

                    b.HasIndex("UserId", "RevokedAt");

                    b.ToTable("AppUserSessions");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.AssistantDailyUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuilderAccessGrantId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservedRequests")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessfulRequests")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("UtcDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BuilderAccessGrantId", "UtcDate")
                        .IsUnique();

                    b.ToTable("AssistantDailyUsages");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.AssistantUsageLease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuilderAccessGrantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("UtcDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BuilderAccessGrantId", "OperationKey")
                        .IsUnique();

                    b.HasIndex("BuilderAccessGrantId", "UtcDate", "ExpiresAtUtc");

                    b.ToTable("AssistantUsageLeases");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.BuilderAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConvertedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("MaximumExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderReference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Origin")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("PinHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("PurchaseTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PurchasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RedeemedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("TrialAssistantRequestsUsed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("TrialDraftExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TrialEditingExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("TrialEditingStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("PurchaseTransactionId")
                        .IsUnique();

                    b.HasIndex("TripId")
                        .IsUnique();

                    b.HasIndex("AppUserId", "IsTrial");

                    b.HasIndex("Status", "ExpiresAtUtc");

                    b.ToTable("BuilderAccessGrants");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.Destination", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("HeroImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasDefaultValue("UTC");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.EmailVerificationChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("RequestIpHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("ResendAvailableAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email", "CreatedAtUtc");

                    b.ToTable("EmailVerificationChallenges");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.FreeMapCity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CenterLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("CenterLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("CitySlug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("ContactUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal>("CoverageRadiusKm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("FreeRadiusKm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId", "CitySlug")
                        .IsUnique();

                    b.HasIndex("IsEnabled", "SortOrder");

                    b.ToTable("FreeMapCities");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ItineraryOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AppliedRevision")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("PreviousRevision")
                        .HasColumnType("integer");

                    b.Property<string>("PreviousStateJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UndoAvailableUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("UndoneAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "AppliedRevision");

                    b.HasIndex("TripId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ItineraryOperations");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ItineraryProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BasedOnRevision")
                        .HasColumnType("integer");

                    b.Property<string>("ChangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("SourceRouteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("SourceRouteId");

                    b.HasIndex("TripId", "ExpiresAtUtc");

                    b.HasIndex("TripId", "AppUserId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("ItineraryProposals");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.MobileDataVersion", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Scope");

                    b.ToTable("MobileDataVersions");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.NotificationDeviceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DisabledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstallationId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Locale")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PushToken")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("RecommendationNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ScheduleRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DisabledAtUtc");

                    b.HasIndex("UserId", "InstallationId")
                        .IsUnique();

                    b.ToTable("NotificationDeviceRegistrations");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.NotificationOutboxItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("DeepLink")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SkippedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("RecommendationId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("Status", "ScheduledForUtc");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("NotificationOutboxItems");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ProductAnalyticsDailyAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EventCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PaywallVariant")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Name", "Source", "Platform", "AppVersion", "PaywallVariant")
                        .IsUnique();

                    b.ToTable("ProductAnalyticsDailyAggregates");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ProductAnalyticsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("AnonymousUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("AppVersion")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("BehaviorConsent")
                        .HasColumnType("boolean");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSandbox")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaywallVariant")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Platform")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("AppUserId", "OccurredAtUtc");

                    b.HasIndex("Name", "OccurredAtUtc");

                    b.ToTable("ProductAnalyticsEvents");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ProductExperimentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Experiment")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId", "Experiment")
                        .IsUnique();

                    b.ToTable("ProductExperimentAssignments");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CitySlug")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CurationNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("ExtraDescription")
                        .HasColumnType("text");

                    b.Property<string>("ExtraDescriptionEn")
                        .HasColumnType("text");

                    b.Property<bool>("IsPriceKnown")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("OpeningHours")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OriginalPrice")
                        .HasColumnType("text");

                    b.Property<string>("PriceLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ProviderPlaceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double?>("Rating")
                        .HasColumnType("double precision");

                    b.Property<string>("RefinedType")
                        .HasColumnType("text");

                    b.Property<string>("RefinedTypeEn")
                        .HasColumnType("text");

                    b.Property<string>("ReservationInstructions")
                        .HasColumnType("text");

                    b.Property<string>("ReservationInstructionsEn")
                        .HasColumnType("text");

                    b.Property<string>("ReservationSource")
                        .HasColumnType("text");

                    b.Property<string>("SourceName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("SuggestedDurationMinutes")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("VerificationConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId", "CitySlug");

                    b.HasIndex("DestinationId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("DestinationId", "ProviderPlaceId")
                        .IsUnique();

                    b.HasIndex("DestinationId", "Title");

                    b.HasIndex("DestinationId", "Category", "Title");

                    b.ToTable("Recommendations");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.RecommendationInteractionSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DistanceMeters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("RecommendationId", "Signal");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.HasIndex("UserId", "TripId", "RecommendationId", "Signal");

                    b.ToTable("RecommendationInteractionSignals");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Airline")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ClientMutationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConfirmationCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DestinationAirport")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("DestinationName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("EndsAt")
                        .HasColumnType("time without time zone");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Flexibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Flexible");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ItemSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Manual");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginAirport")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("OriginName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("Yuku");

                    b.Property<string>("PlanningKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("ManualEvent");

                    b.Property<string>("ProviderPlaceId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SourceName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<TimeOnly>("StartsAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("TimePrecision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("Exact");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("TripDayBlockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Event");

                    b.HasKey("Id");

                    b.HasIndex("RecommendationId");

                    b.HasIndex("TripDayBlockId");

                    b.HasIndex("TripId", "ClientMutationId")
                        .IsUnique();

                    b.HasIndex("TripId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("TripId", "ProviderPlaceId");

                    b.HasIndex("TripId", "RecommendationId");

                    b.HasIndex("TripId", "Date", "StartsAt");

                    b.HasIndex("TripId", "Owner", "Date");

                    b.HasIndex("TripId", "Type", "Date", "StartsAt");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.StoreNotificationReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ProviderNotificationId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Environment", "ProviderNotificationId")
                        .IsUnique();

                    b.ToTable("StoreNotificationReceipts");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.StorePurchaseIntent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DraftSnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("EntryPoint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("Environment")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpaqueAccountId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PaywallVariant")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ProtectedEvidence")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OpaqueAccountId")
                        .IsUnique();

                    b.HasIndex("TripId");

                    b.HasIndex("AppUserId", "TripId", "State");

                    b.ToTable("StorePurchaseIntents");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.StorePurchaseTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AcknowledgedOrConsumed")
                        .HasColumnType("boolean");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("EvidenceFingerprint")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("GrossAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ProtectedProviderToken")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ProviderOriginalTransactionId")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("ProviderTransactionId")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<Guid>("PurchaseIntentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("PurchasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevocationReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("VerifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseIntentId");

                    b.HasIndex("Provider", "Environment", "ProviderTransactionId")
                        .IsUnique();

                    b.ToTable("StorePurchaseTransactions");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ThematicRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<int>("EstimatedTransferMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("TripId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("VisitMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("WarningsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("AppUserId", "UpdatedAtUtc");

                    b.HasIndex("DestinationId", "City", "Theme", "Status");

                    b.ToTable("ThematicRoutes");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ThematicRouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("EstimatedTransferMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ItineraryItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("ThematicRouteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ItineraryItemId");

                    b.HasIndex("RecommendationId");

                    b.HasIndex("ThematicRouteId", "SortOrder")
                        .IsUnique();

                    b.ToTable("ThematicRouteStops");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TravelAssistantFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Intent")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Locale")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseMode")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Signal")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAtUtc");

                    b.HasIndex("RecommendationId", "Signal");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("TravelAssistantFeedbackItems");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TravelChatConversation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastCity")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly?>("LastDate")
                        .HasColumnType("date");

                    b.Property<string>("LastIntent")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("LastLocale")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LastPromptVersion")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("LastRecommendationIds")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("LastResponseMode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PendingPreferenceOriginalMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("PendingPreferencePatchJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PendingPreferenceRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StateJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UpdatedAt");

                    b.ToTable("TravelChatConversations");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TravelDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasMaxLength(220)
                        .HasColumnType("character varying(220)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("TripId", "Category", "SortOrder");

                    b.ToTable("TravelDocuments");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TravelPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSubscription")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("DestinationId", "Price");

                    b.ToTable("TravelPackages");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TravelPreferenceProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AvoidTouristTraps")
                        .HasColumnType("boolean");

                    b.Property<string>("BudgetLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.PrimitiveCollection<List<string>>("DietaryRestrictions")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Dislikes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("FoodPreferences")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Interests")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("MaxWalkingMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("TravelPace")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("TravelPreferenceProfiles");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessPinHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("AccessPinUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AppUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndsOn")
                        .HasColumnType("date");

                    b.Property<string>("ExperienceMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("CuratedPremium");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("PlanRevision")
                        .HasColumnType("integer");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Published");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("StartsOn")
                        .HasColumnType("date");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasDefaultValue("UTC");

                    b.Property<string>("TravelerName")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("AppUserId", "StartsOn");

                    b.HasIndex("DestinationId", "StartsOn");

                    b.HasIndex("PublicationStatus", "StartsOn");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TripDayBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutofillEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("CuratedDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PeriodKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripDayPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripDayPlanId", "PeriodKey")
                        .IsUnique();

                    b.ToTable("TripDayBlocks");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TripDayPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("BaseLatitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("BaseLongitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("BaseProviderPlaceId")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayNumber")
                        .HasColumnType("integer");

                    b.Property<string>("HotelBase")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId", "Date")
                        .IsUnique();

                    b.HasIndex("TripId", "DayNumber")
                        .IsUnique();

                    b.ToTable("TripDayPlans");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TripPlanDraft", b =>
                {
                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<int>("BasePlanRevision")
                        .HasColumnType("integer");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PendingAccessPinHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TripId");

                    b.ToTable("TripPlanDrafts");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.UserEntitlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid?>("TravelPackageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId", "ExpiresAt");

                    b.HasIndex("TravelPackageId", "ExpiresAt");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("UserEntitlements");
                });

            modelBuilder.Entity("RecommendationTravelPackages", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Recommendation", null)
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelCompanion.Api.Models.TravelPackage", null)
                        .WithMany()
                        .HasForeignKey("TravelPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.AppUserSession", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanion.Api.Models.AppUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.AssistantDailyUsage", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.BuilderAccessGrant", "BuilderAccessGrant")
                        .WithMany()
                        .HasForeignKey("BuilderAccessGrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuilderAccessGrant");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.AssistantUsageLease", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.BuilderAccessGrant", "BuilderAccessGrant")
                        .WithMany()
                        .HasForeignKey("BuilderAccessGrantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuilderAccessGrant");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.BuilderAccessGrant", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.AppUser", "AppUser")
                        .WithMany("BuilderAccessGrants")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelCompanion.Api.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelCompanion.Api.Models.StorePurchaseTransaction", "PurchaseTransaction")
                        .WithOne()
                        .HasForeignKey("TravelCompanion.Api.Models.BuilderAccessGrant", "PurchaseTransactionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanion.Api.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");

                    b.Navigation("Destination");

                    b.Navigation("PurchaseTransaction");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.FreeMapCity", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ItineraryOperation", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ItineraryProposal", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.ThematicRoute", "SourceRoute")
                        .WithMany()
                        .HasForeignKey("SourceRouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanion.Api.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceRoute");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.NotificationDeviceRegistration", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.AppUser", "User")
                        .WithMany("NotificationDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.NotificationOutboxItem", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanion.Api.Models.Reservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanion.Api.Models.AppUser", "User")
                        .WithMany("NotificationOutboxItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ProductExperimentAssignment", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.AppUser", "AppUser")
                        .WithMany("ExperimentAssignments")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.Recommendation", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Destination", "Destination")
                        .WithMany("Recommendations")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.RecommendationInteractionSignal", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelCompanion.Api.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelCompanion.Api.Models.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.Reservation", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanion.Api.Models.TripDayBlock", "TripDayBlock")
                        .WithMany("Reservations")
                        .HasForeignKey("TripDayBlockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanion.Api.Models.Trip", "Trip")
                        .WithMany("Reservations")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recommendation");

                    b.Navigation("Trip");

                    b.Navigation("TripDayBlock");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.StorePurchaseIntent", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.AppUser", "AppUser")
                        .WithMany("PurchaseIntents")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelCompanion.Api.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.StorePurchaseTransaction", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.StorePurchaseIntent", "PurchaseIntent")
                        .WithMany("Transactions")
                        .HasForeignKey("PurchaseIntentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseIntent");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ThematicRoute", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelCompanion.Api.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelCompanion.Api.Models.Trip", "Trip")
                        .WithMany("ThematicRoutes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppUser");

                    b.Navigation("Destination");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ThematicRouteStop", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Reservation", "ItineraryItem")
                        .WithMany()
                        .HasForeignKey("ItineraryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanion.Api.Models.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelCompanion.Api.Models.ThematicRoute", "ThematicRoute")
                        .WithMany("Stops")
                        .HasForeignKey("ThematicRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItineraryItem");

                    b.Navigation("Recommendation");

                    b.Navigation("ThematicRoute");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TravelAssistantFeedback", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.TravelChatConversation", "Conversation")
                        .WithMany("FeedbackItems")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelCompanion.Api.Models.Recommendation", "Recommendation")
                        .WithMany()
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelCompanion.Api.Models.AppUser", "User")
                        .WithMany("TravelAssistantFeedbackItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Recommendation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TravelChatConversation", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.AppUser", "User")
                        .WithMany("TravelChatConversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TravelDocument", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Trip", "Trip")
                        .WithMany("Documents")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TravelPackage", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Destination", "Destination")
                        .WithMany("Packages")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TravelPreferenceProfile", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.AppUser", "User")
                        .WithOne("TravelPreferenceProfile")
                        .HasForeignKey("TravelCompanion.Api.Models.TravelPreferenceProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.Trip", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.AppUser", "AppUser")
                        .WithMany("Trips")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TravelCompanion.Api.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Destination");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TripDayBlock", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.TripDayPlan", "TripDayPlan")
                        .WithMany("Blocks")
                        .HasForeignKey("TripDayPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripDayPlan");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TripDayPlan", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Trip", "Trip")
                        .WithMany("DayPlans")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TripPlanDraft", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Trip", "Trip")
                        .WithOne("PlanDraft")
                        .HasForeignKey("TravelCompanion.Api.Models.TripPlanDraft", "TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.UserEntitlement", b =>
                {
                    b.HasOne("TravelCompanion.Api.Models.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.HasOne("TravelCompanion.Api.Models.TravelPackage", "TravelPackage")
                        .WithMany()
                        .HasForeignKey("TravelPackageId");

                    b.HasOne("TravelCompanion.Api.Models.AppUser", "User")
                        .WithMany("Entitlements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("TravelPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.AppUser", b =>
                {
                    b.Navigation("BuilderAccessGrants");

                    b.Navigation("Entitlements");

                    b.Navigation("ExperimentAssignments");

                    b.Navigation("NotificationDevices");

                    b.Navigation("NotificationOutboxItems");

                    b.Navigation("PurchaseIntents");

                    b.Navigation("Sessions");

                    b.Navigation("TravelAssistantFeedbackItems");

                    b.Navigation("TravelChatConversations");

                    b.Navigation("TravelPreferenceProfile");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.Destination", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("Recommendations");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.StorePurchaseIntent", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.ThematicRoute", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TravelChatConversation", b =>
                {
                    b.Navigation("FeedbackItems");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.Trip", b =>
                {
                    b.Navigation("DayPlans");

                    b.Navigation("Documents");

                    b.Navigation("PlanDraft");

                    b.Navigation("Reservations");

                    b.Navigation("ThematicRoutes");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TripDayBlock", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TravelCompanion.Api.Models.TripDayPlan", b =>
                {
                    b.Navigation("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
